#page title
page_title                                :                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6744281169                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/MyDailyDadJokeAppIcon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : My Daily Dad Joke                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The ultimate app for eye-rolls and chuckles.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : David Gates
your_link                                 :
your_city                                 : California
email_address                             : dappernarwhalstudios+support@gmail.com
linkedin_username                         :
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           : dappernarwhalstudios
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features:
  - title: A New Joke Every Day
    description: Start your day with a fresh dad joke delivered daily—no repeats, just pure pun power.
    fontawesome_icon_name: calendar-alt

  - title: Home Screen Widget
    description: Never miss a laugh with a convenient widget that puts your daily joke front and center.
    fontawesome_icon_name: th-large

  - title: Save and Share Favorites
    description: Mark your favorite jokes and easily share them with friends and family.
    fontawesome_icon_name: heart

  - title: Clean and Simple Design
    description: Enjoy a clutter-free experience that keeps the jokes front and center.
    fontawesome_icon_name: smile

  - title: Ad-Free Upgrade Available
    description: Go ad-free with a one-time upgrade and support the app while keeping the laughs coming.
    fontawesome_icon_name: hand-holding-heart

  - title: Built with SwiftUI
    description: Smooth animations and native performance using Apple’s latest UI framework.
    fontawesome_icon_name: rocket




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
